name: amorium
description: Spread Love!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_storage: ^10.3.7
  firebase_core: ^1.21.1
  cloud_firestore: ^3.4.6
  flutter_riverpod: ^1.0.4
  firebase_auth: ^3.7.0
  contacts_service: ^0.6.3
  permission_handler: ^10.0.0
  image_picker: ^0.8.5+3
  enough_giphy_flutter: ^0.3.0
  intl: ^0.17.0
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Italic.ttf
          style: italic
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Gilroy-Heavy.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-HeavyItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 900
        - asset: assets/fonts/Gilroy-BlackItalic.ttf
          weight: 900
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700