// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB52uCugLt-NVYkDHKREsF-Kv4Z2-KzfQY',
    appId: '1:472893884062:web:8bb368f805a05d3b611d8f',
    messagingSenderId: '472893884062',
    projectId: 'amorium-amorion',
    authDomain: 'amorium-amorion.firebaseapp.com',
    storageBucket: 'amorium-amorion.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkcV_26qsL_-N3PFpFpK4mneYTbgoqgo4',
    appId: '1:472893884062:android:7c7298daae5d3706611d8f',
    messagingSenderId: '472893884062',
    projectId: 'amorium-amorion',
    storageBucket: 'amorium-amorion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6YgjxTXogjqL1hVEnwZn2eWMux2ubb3g',
    appId: '1:472893884062:ios:953be8d946431895611d8f',
    messagingSenderId: '472893884062',
    projectId: 'amorium-amorion',
    storageBucket: 'amorium-amorion.appspot.com',
    iosClientId: '472893884062-lard8s29gsngfjnu4i561n29j92o5ed0.apps.googleusercontent.com',
    iosBundleId: 'com.amorion.amorium',
  );
}
